service: central-currency-web

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-stage-manager
#  - serverless-step-functions
custom:
  defaultStage: dev
  stages:
    - test
    - dev
    - prod
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, ${self:custom.defaultStage}}
  versionFunctions: false

#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "states:*"
#      Resource:
#        - "*"
#    - Effect: "Allow"
#      Action:
#        - "ssm:GetParameter"
#      Resource:
#        - "*"
#    - Effect: "Allow"
#      Action:
#        - "s3:*"
#      Resource:
#        - "*"
#    - Effect: "Allow"
#      Action:
#        - "dynamodb:*"
#      Resource:
#        - "*"
#    - Effect: "Allow"
#      Action:
#        - "logs:*"
#      Resource: "*"

#  environment:


package:
  exclude:
    - env/**
    - venv/**
    - .idea/**
    - .vscode/**
    - tests/**
    - node_modules/**


#functions:

