service: central-currency-web

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-stage-manager
custom:
  defaultStage: "dev"
  stages:
    - test
    - dev
    - prod
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

  CURRENCY_RATES_TABLE: ${self:provider.stage}-currency-rates

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, ${self:custom.defaultStage}}
  versionFunctions: false

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"

  environment:
    CURRENCY_RATES_TABLE: ${self:custom.CURRENCY_RATES_TABLE}


package:
  exclude:
    - env/**
    - venv/**
    - .idea/**
    - .vscode/**
    - tests/**
    - node_modules/**


functions:
  parsePrivat:
    handler: src.handlers.parsers.parse_privat
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: false


resources:
  Resources:
    currencyRatesTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: rateId
            AttributeType: S
        KeySchema:
          - AttributeName: rateId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.CURRENCY_RATES_TABLE}
